### PR TITLE
updating the write momdp file

### PR DESCRIPTION
**Pull request by miladm12**
Seems that dim function does not support for 4-dimensional matrices. Also fixed a bug.

### CODE REVIEW

**Comment by cboettig** [comment]
Thanks. 

`dim` should work fine for 4-d matrices (called `array`s in R), e.g.:

```r
# a new 4D array (4 x 5 x 6 x 7 matrix) filled with 0s
X <- array(0, dim = c(4,5,6,7))
dim(X)[4] # is 7 
```

 but perhaps `O` is a list of matrices or some other structure instead of an array? (check `class(O)`).  Anyway we can use `size`, but just include the code for the custom `size` function here.  (I switched all the `size` calls to `dim` calls earlier just to make the code a bit easier for most R people to read, but of course we can use `size` if we need that custom handling of different objects.


Can you add some basic tests for each of the momdp read/write functions to test that they have the expected behavior?  You can look at the current tests: https://github.com/cboettig/appl/tree/master/tests/testthat and see http://r-pkgs.had.co.nz/tests.html for a good intro to writing tests.  Thanks!

**Comment by cboettig** [comment]
hmm, also looks like we have some merge conflicts.  You can pull from upstream (`git pull https://github.com/cboettig/appl` and merge manually to your fork, then push back to your fork to resolve.  Sorry these things can be a nuisance but worth learning in the long run).

**Comment by miladm12** [comment]
Did I fix this or not yet? Can you now merge the request?

**Comment by cboettig** [comment]
Sorry, but looks like you still have the `≥>>>>>>>>` etc symbols that the merge conflict added to indicate the conflicting lines.  You'll need to remove those.   Also, I don't see the added code for `size` or using`dim` instead.  

Also it would be good to add the tests before we merge, that would have caught the error about the merge lines and the missing definition for the `size` function.  

Let me know if any of that doesn't make sense

**Comment by miladm12** [comment]
size is already in Fish_Dynamic_Fun which will be loaded as a function in the package. 

I am working on the samsung grant right now but I will work on the test later today and will send you for review.

**Comment by cboettig** [comment]
No problem, whenever you get to it.  I know `size` is in the other package (pomdp-fish), but that package not a dependency of this package since it is specific to our fisheries applications and this is not.  Also I think it would be cleaner to use dim throughout.  What structure should `O` be in this case?  Is it a list of 3d arrays or a 4 d array, or something else?

**Comment by miladm12** [comment]
O = array(0,dim = c(Num_ps,Num_z,Num_a,Num_fs)) so it is a 4-dim array but for some reason dim was not able to identify the fourth dimension. I'll fix this later, don't worry about it.

**Comment by miladm12** [comment]
BTW, how are we doing on the manuscript#2? Have you had a change to go through it?

**Comment by cboettig** [comment]
Thanks!  Looks like the test is failing though -- see the automated log from Travis above.  The link I have above on testing will also explain how to run tests locally to make sure everything is working.

**Comment by miladm12** [comment]
I'm not getting the same error anymore, but it seems non of the tests works on my local directory. not sure why is that but need to figure it out. Can you check the updated file and see if it still fails?

**Comment by cboettig** [comment]
Hmm, all the tests should work locally.  you may need to install the package first.  The best way to run the tests is to just use the command `devtools::check()`, which should make sure the right things are installed first.  

Sure, gimme a sec and I'll pull down your branch and take a look.

**Comment by miladm12** [comment]
for me all the test fails in my local directory. I did install appl and
other packages needed. It does not give me why it's failing. Does the
parallelization in pomdp needs installation of a package?

On Thu, Jun 2, 2016 at 1:03 PM, Carl Boettiger <notifications@github.com>
wrote:

> Hmm, all the tests should work locally. you may need to install the
> package first. The best way to run the tests is to just use the command
> devtools::check(), which should make sure the right things are installed
> first.
>
> Sure, gimme a sec and I'll pull down your branch and take a look.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cboettig/appl/pull/5#issuecomment-223405516>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANis7Fdd10DIrQMwdbC7nxQpvUHSPjjYks5qHzcpgaJpZM4IrK2S>
> .
>



-- 
Milad Memarzadeh, Ph.D.
Postdoctoral Scholar
Department of Environmental Science, Policy and Management
University of California, Berkeley
201 Wellman Hall, Berkeley, CA 94720

**Comment by cboettig** [comment]
hmm, that should be in base.  Can try logging into jetstream.carlboettiger.info instance and run the tests there to compare (I just did, and get the same thing as the automated travis check).  maybe it's just failing on all tests on mac?  still, devtools::check() should give some output; can you paste whatever it outputs?

**Comment by miladm12** [comment]
this is the output of the devtools::check():

Failed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
1. Error: appl base functions generates a policy (@test-appl.R#9)
-----------------------------------------------------------------------------------------------------------
Call to pomdpsol failed with error: 139
1: pomdpsol(model, output = f, precision = 10) at
/Users/Milad/Documents/appl/tests/testthat/test-appl.R:9
2: exec_program("pomdpsol", args, stdout = f, stderr = stderr) at
/Users/Milad/Documents/appl/R/appl.R:42
3: stop("Call to ", program, " failed with error: ", res) at
/Users/Milad/Documents/appl/R/appl.R:102

2. Error: pomdpeval, polgraph and pomdpsim run without error
(@test-appl.R#21)
----------------------------------------------------------------------------------------------
Call to pomdpsol failed with error: 139
1: pomdpsol(model, output = policy, precision = 10) at
/Users/Milad/Documents/appl/tests/testthat/test-appl.R:21
2: exec_program("pomdpsol", args, stdout = f, stderr = stderr) at
/Users/Milad/Documents/appl/R/appl.R:42
3: stop("Call to ", program, " failed with error: ", res) at
/Users/Milad/Documents/appl/R/appl.R:102

3. Error: pomdp functions generates a policy (@test-pomdp.R#7)
--------------------------------------------------------------------------------------------------------------
Call to pomdpsol failed with error: 139
1: pomdp(transition, observation, reward, discount, precision = 10) at
/Users/Milad/Documents/appl/tests/testthat/test-pomdp.R:7
2: parallel::mclapply(1:Num_z, function(i) {
       belief = initial * t(O[, i, 1])
       belief = normalize(belief)
       if (any(is.nan(belief)) || sum(belief) == 0) {
           list(value = 0, policy = 0, alpha = list(), alpha_action =
list())
       }
       else {
           infile <- tempfile("input", fileext = ".pomdp")
           outfile <- tempfile("output", fileext = ".policy")
           write_pomdpx(T, O, R, GAMMA, belief, file = infile)
           pomdpsol(infile, outfile, ...)
           out = read_policy(belief, file = outfile)
           list(value = out[[1]], policy = out[[2]], alpha = out[[3]],
alpha_action = out[[4]])
       }
   }, mc.cores = mc.cores) at /Users/Milad/Documents/appl/R/pomdp.R:39
3: lapply(X = X, FUN = FUN, ...)
4: FUN(X[[i]], ...) at /Users/Milad/Documents/appl/R/pomdp.R:39
5: pomdpsol(infile, outfile, ...) at
/Users/Milad/Documents/appl/R/pomdp.R:55
6: exec_program("pomdpsol", args, stdout = f, stderr = stderr) at
/Users/Milad/Documents/appl/R/appl.R:42
7: stop("Call to ", program, " failed with error: ", res) at
/Users/Milad/Documents/appl/R/appl.R:102

4. Error: write_momdpx writes an xml problem file (@test-write_momdpx.R#4)
--------------------------------------------------------------------------------------------------
unused argument (sdlog = 0.282918199615253)
1: source(system.file("examples/fisheries_ex_NS.R", package = "appl")) at
/Users/Milad/Documents/appl/tests/testthat/test-write_momdpx.R:4
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(expr, envir, enclos)
5: dlnorm(states_full, log(states_full[j], sdlog = sigma_g)) at
/Users/Milad/Documents/appl/inst/examples/fisheries_ex_NS.R:55

DONE
========================================================================================================================================================================
> devtools::check()
Updating appl documentation
Loading appl
Setting env vars
------------------------------------------------------------------------------------------------------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building appl
---------------------------------------------------------------------------------------------------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file
--no-environ --no-save --no-restore --quiet CMD build
'/Users/Milad/Documents/appl' --no-resave-data  \
  --no-manual

* checking for file ‘/Users/Milad/Documents/appl/DESCRIPTION’ ... OK
* preparing ‘appl’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘appl_0.2.1.tar.gz’

Setting env vars
------------------------------------------------------------------------------------------------------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking appl
---------------------------------------------------------------------------------------------------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file
--no-environ --no-save --no-restore --quiet CMD check  \

'/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpB6MkB1/appl_0.2.1.tar.gz'
--as-cran --timings --no-manual

* using log directory
‘/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck’
* using R version 3.2.3 (2015-12-10)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘appl/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘appl’ version ‘0.2.1’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘appl’ can be installed ... WARNING
Found the following significant warnings:
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1267:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1281:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/SparseTable.cpp:525:1: warning: control may reach
end of non-void function [-Wreturn-type]
Found the following additional warnings:
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1267:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1281:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/SparseTable.cpp:525:1: warning: control may reach
end of non-void function [-Wreturn-type]
See
‘/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/00install.out’
for details.
* checking installed package size ... NOTE
  installed size is  5.1Mb
  sub-directories of 1Mb or more:
    bin   4.6Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ...
OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking compiled code ... OK
* checking examples ... ERROR
Running examples in ‘appl-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: pomdpsol
> ### Title: APPL wrappers
> ### Aliases: SARSOP appl polgraph pomdpconvert pomdpeval pomdpsim pomdpsol
>
> ### ** Examples
>
> model <- system.file("models/example.pomdp", package = "appl")
> policy <- tempfile()
> pomdpsol(model, output = policy, timeout = 2)
sh: line 1: 27209 Segmentation fault: 11
 '/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/appl/bin/pomdpsol'
/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/appl/models/example.pomdp
--output
/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpDiO0aZ/file6a4712001f55
--precision 1 --timeout 2 >
'/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpDiO0aZ/file6a4746090eae'
Error in exec_program("pomdpsol", args, stdout = f, stderr = stderr) :
  Call to pomdpsol failed with error: 139
Calls: pomdpsol -> exec_program
Execution halted
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  3: eval(ei, envir)
  4: eval(expr, envir, enclos)
  5: dlnorm(states_full, log(states_full[j], sdlog = sigma_g))

  testthat results
================================================================
  OK: 1 SKIPPED: 0 FAILED: 4
  1. Error: appl base functions generates a policy (@test-appl.R#9)
  2. Error: pomdpeval, polgraph and pomdpsim run without error
(@test-appl.R#21)
  3. Error: pomdp functions generates a policy (@test-pomdp.R#7)
  4. Error: write_momdpx writes an xml problem file
(@test-write_momdpx.R#4)

  Error: testthat unit tests failed
  Execution halted
* DONE

Status: 2 ERRORs, 1 WARNING, 1 NOTE
See

‘/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/00check.log’
for details.

R CMD check results
2 errors | 1 warning  | 1 note
checking examples ... ERROR
Running examples in ‘appl-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: pomdpsol
> ### Title: APPL wrappers
> ### Aliases: SARSOP appl polgraph pomdpconvert pomdpeval pomdpsim pomdpsol
>
> ### ** Examples
>
> model <- system.file("models/example.pomdp", package = "appl")
> policy <- tempfile()
> pomdpsol(model, output = policy, timeout = 2)
sh: line 1: 27209 Segmentation fault: 11
 '/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/appl/bin/pomdpsol'
/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/appl/models/example.pomdp
--output
/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpDiO0aZ/file6a4712001f55
--precision 1 --timeout 2 >
'/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpDiO0aZ/file6a4746090eae'
Error in exec_program("pomdpsol", args, stdout = f, stderr = stderr) :
  Call to pomdpsol failed with error: 139
Calls: pomdpsol -> exec_program
Execution halted

checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  3: eval(ei, envir)
  4: eval(expr, envir, enclos)
  5: dlnorm(states_full, log(states_full[j], sdlog = sigma_g))

  testthat results
================================================================
  OK: 1 SKIPPED: 0 FAILED: 4
  1. Error: appl base functions generates a policy (@test-appl.R#9)
  2. Error: pomdpeval, polgraph and pomdpsim run without error
(@test-appl.R#21)
  3. Error: pomdp functions generates a policy (@test-pomdp.R#7)
  4. Error: write_momdpx writes an xml problem file
(@test-write_momdpx.R#4)

  Error: testthat unit tests failed
  Execution halted

checking whether package ‘appl’ can be installed ... WARNING
Found the following significant warnings:
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1267:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1281:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/SparseTable.cpp:525:1: warning: control may reach
end of non-void function [-Wreturn-type]
Found the following additional warnings:
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1267:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/FactoredPomdp.cpp:1281:1: warning: control may
reach end of non-void function [-Wreturn-type]
  appl-0.96/Parser/POMDPX/SparseTable.cpp:525:1: warning: control may reach
end of non-void function [-Wreturn-type]
See
‘/private/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T/RtmpB6MkB1/appl.Rcheck/00install.out’
for details.

checking installed package size ... NOTE
  installed size is  5.1Mb
  sub-directories of 1Mb or more:
    bin   4.6Mb

On Thu, Jun 2, 2016 at 4:08 PM, Carl Boettiger <notifications@github.com>
wrote:

> hmm, that should be in base. Can try logging into
> jetstream.carlboettiger.info instance and run the tests there to compare
> (I just did, and get the same thing as the automated travis check). maybe
> it's just failing on all tests on mac? still, devtools::check() should give
> some output; can you paste whatever it outputs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cboettig/appl/pull/5#issuecomment-223449033>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANis7GcFSlfD10zgbeusVCvC0KPKLsuIks5qH2JngaJpZM4IrK2S>
> .
>



-- 
Milad Memarzadeh, Ph.D.
Postdoctoral Scholar
Department of Environmental Science, Policy and Management
University of California, Berkeley
201 Wellman Hall, Berkeley, CA 94720

**Comment by cboettig** [comment]
weird, you're getting a segfault on running any tests that use `appl::pomdpsol`.  Just tried on my mac and I don't get that error there either.

**Comment by miladm12** [comment]
any idea why this is happening?

**Comment by cboettig** [comment]
good question, we'd have to experiment a bit.  If you run any of the test files interactively from RStudio, do they work without error?  If that works, try running the tests individually with; e.g. `testthat::test_file("tests/testthat/test-appl.R")`

Also, can you paste the contents of `sessionInfo()` output here after running a failing test?

**Comment by miladm12** [comment]
only write_pomdp doesn't fail, the rest fails.

this is the output of sessionInfo():

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] appl_0.2.1     testthat_1.0.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5     roxygen2_5.0.1  digest_0.6.9    crayon_1.3.1    withr_1.0.1     R6_2.1.1        git2r_0.15.0    magrittr_1.5    httr_1.1.0      stringi_1.0-1  
[11] curl_0.9.7      xml2_0.1.2      devtools_1.11.1 tools_3.2.3     stringr_1.0.0   parallel_3.2.3  memoise_1.0.0

**Comment by cboettig** [comment]
I see that they fail when you run devtools::check(), but they also fail when you try and run interactively? 
that is, any time you run appl::pomdpsol on your machine, you just get an error?  If that's the case, was appl::pomdpsol() ever running without error on your machine?

If `appl::pomdpsol()` is working for you in other cases, we should be able to track down what's different about the test examples for you.  You might try uninstalling the package (e.g. `devtools::uninstall()`, clearing the workspace and restarting the R session first to get a clean environment.

**Comment by miladm12** [comment]
I never used pomdpsol before on my machine and it fails right now. The error is this:

Error in exec_program("pomdpsol", args, stdout = f, stderr = stderr) : 
  Call to pomdpsol failed with error: 139

**Comment by cboettig** [comment]
ok, good to know.  so let's backtrack a bit.  try:

```r
devtools::uninstall()
devtools::install_github("ropensci/appl")
model <- system.file("models/example.pomdp", package = "appl")
policy <- appl::pomdpsol(model)
```

and let me know if you get the same error?

**Comment by miladm12** [comment]
different error:

Loading the model ...
  input file   : /Library/Frameworks/R.framework/Versions/3.2/Resources/library/appl/models/example.pomdp
  loading time : 0.10s 

SARSOP initializing ...
Error in exec_program("pomdpsol", args, stdout = stdout) : 
  Call to pomdpsol failed with error: 11

**Comment by cboettig** [comment]
Well, I think that's progress of a sort!  Can you give me the output of

```r
model <- system.file("models/example.pomdp", package = "appl")
binpath <- system.file("bin", package = "appl")
system2(paste0(binpath, "/pomdpsol"), model)
```



Another thing to check is upgrading your R version to 3.3.0, and repeat the same uninstall/reinstall:

```r
devtools::uninstall()
devtools::install_github("ropensci/appl")
model <- system.file("models/example.pomdp", package = "appl")
policy <- appl::pomdpsol(model)
```

**Comment by miladm12** [comment]
this is the output:

Loading the model ...
  input file   : /Library/Frameworks/R.framework/Versions/3.2/Resources/library/appl/models/example.pomdp
  loading time : 0.10s 

SARSOP initializing ...

**Comment by cboettig** [comment]
no error? look like sarsop is still running then?

**Comment by miladm12** [comment]
It just pastes that and that's it. sarsop doesn't run

**Comment by cboettig** [comment]
sorry, I meant the pomdsol C++ code appears to be running, since it produces the intialization output, the sarsop subroutine part I guess isn't running then?  If R doesn't return the command prompt `>`, then something is running or hanging -- you can check if anything is running is mac system manager?

kind of sounds like part of the sarsop cpp code isn't compiling correctly when `appl` installs.... do you get any errors or warnings when you ran 

```r
devtools::uninstall()
devtools::install_github("ropensci/appl")
```

**Comment by miladm12** [comment]
Yes, I get a lot of warnings but no error.

**Comment by miladm12** [comment]
I did update both r and rstudio on my machine. Still error 11 is happening. Could it be because of the OS El capitan? What's the OS on your mac that you tested?

**Comment by cboettig** [comment]
I'm also on `El Capitan`.  I suppose there could be compiler differences still from the XCode version or something

**Comment by miladm12** [comment]
Let me update my OS and Xcode, and see if it fixes it.

**Comment by cboettig** [comment]
Worth a shot.  Also make sure that the previous version is fully uninstalled and that the re-install is also recompiling the C code (by default it tries to save time by using previous complied libraries).  sorry for the nuisance.

**Comment by miladm12** [comment]
Do you mean previous versions of xcode or sarsop?

On Friday, June 3, 2016, Carl Boettiger <notifications@github.com> wrote:

> Worth a shot. Also make sure that the previous version is fully
> uninstalled and that the re-install is also recompiling the C code (by
> default it tries to save time by using previous complied libraries). sorry
> for the nuisance.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cboettig/appl/pull/5#issuecomment-223677273>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANis7KM_R7oIHEbrjFocw9CiDxn8d07mks5qIIVfgaJpZM4IrK2S>
> .
>


-- 
Milad Memarzadeh, Ph.D.
Postdoctoral Scholar
Department of Environmental Science, Policy and Management
University of California, Berkeley
201 Wellman Hall, Berkeley, CA 94720

**Comment by cboettig** [comment]
The version of SARSOP installed by the `appl` R package.  I just noticed, you said the error message had the line:

```
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/appl/models/example.pomdp
```

which I believe implies it is running a version of appl installed on R 3.2.  Not sure that devtools::uninstall() purges that.  I would try manually deleting `/Library/Frameworks/R.framework/Versions/3.2/Resources/library/appl`.  Also see if you have a 

`/Library/Frameworks/R.framework/Versions/3.3` directory now that you upgraded R

**Comment by miladm12** [comment]
OK, now the appl runs and works but the test still fails. 


> testthat::test_file("tests/testthat/test-appl.R")
appl: 
sh: line 1:  1381 Segmentation fault: 11  '/Users/Milad/Documents/appl/inst/bin/pomdpsol' /Users/Milad/Documents/appl/inst/models/example.pomdp --output /var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpPFHfsT/file53b65582074 --precision 10 > '/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpPFHfsT/file53b7cbad3a6'
1
sh: line 1:  1383 Segmentation fault: 11  '/Users/Milad/Documents/appl/inst/bin/pomdpsol' /Users/Milad/Documents/appl/inst/models/example.pomdp --output /var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpPFHfsT/file53b4d9d7743 --precision 10 > '/var/folders/v6/yrpxhpcd45v99bhv5j3mdf4r0000gn/T//RtmpPFHfsT/file53b1d00f784'
2

Failed ---------------------------------------------------------------------------------------------------------
1. Error: appl base functions generates a policy (@test-appl.R#9) ----------------------------------------------
Call to pomdpsol failed with error: 139
1: pomdpsol(model, output = f, precision = 10) at tests/testthat/test-appl.R:9
2: exec_program("pomdpsol", args, stdout = f, stderr = stderr) at /Users/Milad/Documents/appl/R/appl.R:42
3: stop("Call to ", program, " failed with error: ", res) at /Users/Milad/Documents/appl/R/appl.R:102

2. Error: pomdpeval, polgraph and pomdpsim run without error (@test-appl.R#21) ---------------------------------
Call to pomdpsol failed with error: 139
1: pomdpsol(model, output = policy, precision = 10) at tests/testthat/test-appl.R:21
2: exec_program("pomdpsol", args, stdout = f, stderr = stderr) at /Users/Milad/Documents/appl/R/appl.R:42
3: stop("Call to ", program, " failed with error: ", res) at /Users/Milad/Documents/appl/R/appl.R:102

DONE ===========================================================================================================
>

**Comment by miladm12** [comment]
and before the test appl was working but after the test failed now appl does not work as well.

**Comment by cboettig** [comment]
looks like there's some confusing stuff going on with paths and which version is being run. You can see the error is calling: `/Users/Milad/Documents/appl/inst/bin/pomdpsol`, which must not be built correctly.  R should install the package in `/Library/Frameworks/R.framework/Versions/3.3`

I think somehow you have a corrupted binary that keeps messing things up. (I know it's also tricky to tell if we are using the `ropensci/appl`, the `cboettig/appl` or the `miladm12/appl` version).  

I would start by removing any occurance of `appl` in `/Library/Frameworks/R.framework/Versions/3.3`, and then I would go to a new test directory within your `Documents` and clone a fresh copy of `cboettig/appl`, and try installing that first and then running the test.  If it errors, check the path and see if it's using a local binary (e.g. begins with `/Users/Milad`...) or the system one.

**Comment by miladm12** [comment]
Ok, I guess the problem is fixed now. I'm working on fixing the momdp test file. Although, it doesn't exactly give me where the error is coming from, while when you sent it to me, it was referring to specific line in code. How can I extract that kind of information.

**Comment by cboettig** [comment]
If there's an error message, it should give the path somewhere in the message (like in the messages you posted above).  Otherwise, you can try `system.file("bin", package = "appl")` which should tell you what path it is using for the binary.

**Comment by miladm12** [comment]
Ok, it passes the test on my machine now. check if it passes on yours too and then you can merge.

**Comment by miladm12** [comment]
thanks for all the help and info. I'm still getting into this :)

**Comment by cboettig** [comment]
yay, looks like all checks passing on GitHub too.

**Pull request merged**
